version: '2'
services:
  ui:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
    tty: true
    volumes:
      - .:/app
  server:
    build: ./server
    ports:
      - '9000:9000'